package com.virtualeduc.tuescuelavirtual.models.mappers;

import com.virtualeduc.tuescuelavirtual.models.Alumno;
import com.virtualeduc.tuescuelavirtual.models.DTOS.AlumnoDTO;

import java.util.function.Function;

public class AlumnoToAlumnoDtoMapper {

    public AlumnoDTO obtenerAlumnoDto(Alumno alumno) {
        AlumnoDTO alumnoDTO=new AlumnoDTO();
        alumnoDTO.setTextoDirPpalAl(alumno.getDirPpalAl());
        String[] arrOfStrDirPpalAl = alumnoDTO.getTextoDirPpalAl().split(",");
        alumnoDTO.setTextoDirSecAl(alumno.getDirSecAl());
        String[] arrOfStrDirSecAl = alumnoDTO.getTextoDirSecAl().split(",");
        alumnoDTO.setTextoTlfPpalAl(alumno.getTlfPpalAl());
        String[] arrOfStrTlfPpalAl = alumnoDTO.getTextoTlfPpalAl().split("-");
        alumnoDTO.setTextoTlfSecAl(alumno.getTlfSecAl());
        String[] arrOfStrTlfSecAl = alumnoDTO.getTextoTlfSecAl().split("-");
        alumnoDTO.setTextoDirPpalRpr1(alumno.getRpr1().getDirPpalRpr());
        String[] arrOfStrDirPpalRpr1 = alumnoDTO.getTextoDirPpalRpr1().split(",");
        alumnoDTO.setTextoDirSecRpr1(alumno.getRpr1().getDirSecRpr());
        String[] arrOfStrDirSecRpr1 = alumnoDTO.getTextoDirSecRpr1().split(",");
        alumnoDTO.setTextoTlfPpalRpr1(alumno.getRpr1().getTlfPpalRpr());
        String[] arrOfStrTlfPpalRpr1 = alumnoDTO.getTextoTlfPpalRpr1().split("-");
        alumnoDTO.setTextoTlfSecRpr1(alumno.getRpr1().getTlfSecRpr());
        String[] arrOfStrTlfSecRpr1 = alumnoDTO.getTextoTlfSecRpr1().split("-");
        alumnoDTO.setTextoTlfPpalRpr2(alumno.getRpr2().getDirPpalRpr());
        String[] arrOfStrDirPpalRpr2 =alumnoDTO.getTextoTlfPpalRpr2().split(",");
        alumnoDTO.setTextoDirSecRpr2(alumno.getRpr2().getDirSecRpr());
        String[] arrOfStrDirSecRpr2 = alumnoDTO.getTextoDirSecRpr2().split(",");
        alumnoDTO.setTextoTlfPpalRpr2(alumno.getRpr2().getTlfPpalRpr());
        String[] arrOfStrTlfPpalRpr2 = alumnoDTO.getTextoTlfPpalRpr2().split("-");
        alumnoDTO.setTextoTlfSecRpr2(alumno.getRpr2().getTlfSecRpr());
        String[] arrOfStrTlfSecRpr2 = alumnoDTO.getTextoTlfSecRpr2().split("-");
        alumnoDTO.setIdAl(alumno.getIdAl());
        alumnoDTO.setTipoDocAl(alumno.getTipoDocAl());
        alumnoDTO.setNumDocAl(alumno.getNumDocAl());
        alumnoDTO.setPrimNombAl(alumno.getPrimNombAl());
        alumnoDTO.setSegNombAl(alumno.getSegNombAl());
        alumnoDTO.setPrimApellAl(alumno.getPrimApellAl());
        alumnoDTO.setSegApellAl(alumno.getSegApellAl());
        alumnoDTO.setSexoAl(alumno.getSexoAl());
        alumnoDTO.setFechNacAl(alumno.getFechNacAl());
        alumnoDTO.setEdadAl(alumno.getEdadAl());
        alumnoDTO.setTextoDirPpalAl(arrOfStrDirPpalAl[0]);
        alumnoDTO.setEstadodirppalest(arrOfStrDirPpalAl[1]);
        alumnoDTO.setMunicipiodirppalest(arrOfStrDirPpalAl[2]);
        alumnoDTO.setCiudaddirppalest(arrOfStrDirPpalAl[3]);
        alumnoDTO.setParroquiadirppalest(arrOfStrDirPpalAl[4]);
        alumnoDTO.setCodpostaldirppalest(arrOfStrDirPpalAl[5]);
        alumnoDTO.setTextoDirSecAl(arrOfStrDirSecAl[0]);
        alumnoDTO.setEstadodirsecest(arrOfStrDirSecAl[1]);
        alumnoDTO.setMunicipiodirsecest(arrOfStrDirSecAl[2]);
        alumnoDTO.setCiudaddirsecest(arrOfStrDirSecAl[3]);
        alumnoDTO.setParroquiadirsecest(arrOfStrDirSecAl[4]);
        alumnoDTO.setCodpostaldirsecest(arrOfStrDirSecAl[5]);
        alumnoDTO.setCodoperadorappalest(arrOfStrTlfPpalAl[0]);
        alumnoDTO.setTextoTlfPpalAl(arrOfStrTlfPpalAl[1]);
        alumnoDTO.setCodoperadorasecest(arrOfStrTlfSecAl[0]);
        alumnoDTO.setTextoTlfSecAl(arrOfStrTlfSecAl[1]);
        alumnoDTO.setEmailAl(alumno.getEmailAl());
        alumnoDTO.setFechIngAl(alumno.getFechIngAl());
        alumnoDTO.setStatus(alumno.getStatus());
        alumnoDTO.setIdRpr1(alumno.getRpr1().getIdRpr());
        alumnoDTO.setIdRpr2(alumno.getRpr2().getIdRpr());
        alumnoDTO.setIdCurso(alumno.getCurso().getIdCurso());
        alumnoDTO.setFechaCreacion(alumno.getFechaCreacion());
        alumnoDTO.setAnnio(alumno.getCurso().getAnnio().getAnnio());
        alumnoDTO.setAnnioescolar(alumno.getCurso().getAnnioEscolar().getIntAnnioEsc());
        alumnoDTO.setSeccion(alumno.getCurso().getSeccion().getSeccion());
        alumnoDTO.setTurno(alumno.getCurso().getTurno().getTurno());
        alumnoDTO.setEspecialidad(alumno.getCurso().getAnnio().getEspecialidad());
        alumnoDTO.setNivel(alumno.getCurso().getAnnio().getNivel());
        alumnoDTO.setTipoDocRep1(alumno.getRpr1().getTipoDocRpr());
        alumnoDTO.setNumDocRep1(alumno.getRpr1().getNumDocRpr());
        alumnoDTO.setPrimNombRpr1(alumno.getRpr1().getPrimNombRpr());
        alumnoDTO.setSegNombRpr1(alumno.getRpr1().getSegNombRpr());
        alumnoDTO.setPrimApellRpr1(alumno.getRpr1().getPrimApellRpr());
        alumnoDTO.setSegApellRpr1(alumno.getRpr1().getSegApellRpr());
        alumnoDTO.setSexoRpr1(alumno.getRpr1().getSexoRpr());
        alumnoDTO.setFechNacRpr1(alumno.getRpr1().getFechNacRpr());
        alumnoDTO.setEdadRpr1(alumno.getRpr1().getEdadRpr());
        alumnoDTO.setEdoCivRpr1(alumno.getRpr1().getEdoCivRpr());
        alumnoDTO.setParRpr1(alumno.getParRpr1());
        alumnoDTO.setTextoDirPpalRpr1(arrOfStrDirPpalRpr1[0]);
        alumnoDTO.setEstadodirppalrep1(arrOfStrDirPpalRpr1[1]);
        alumnoDTO.setMunicipiodirppalrep1(arrOfStrDirPpalRpr1[2]);
        alumnoDTO.setCiudaddirppalrep1(arrOfStrDirPpalRpr1[3]);
        alumnoDTO.setParroquiadirppalrep1(arrOfStrDirPpalRpr1[4]);
        alumnoDTO.setCodpostaldirppalrep1(arrOfStrDirPpalRpr1[5]);
        alumnoDTO.setTextoDirSecRpr1(arrOfStrDirSecRpr1[0]);
        alumnoDTO.setEstadodirsecrep1(arrOfStrDirSecRpr1[1]);
        alumnoDTO.setMunicipiodirsecrep1(arrOfStrDirSecRpr1[2]);
        alumnoDTO.setCiudaddirsecrep1(arrOfStrDirSecRpr1[3]);
        alumnoDTO.setParroquiadirsecrep1(arrOfStrDirSecRpr1[4]);
        alumnoDTO.setCodpostaldirsecrep1(arrOfStrDirSecRpr1[5]);
        alumnoDTO.setCodoperadorappalrep1(arrOfStrTlfPpalRpr1[0]);
        alumnoDTO.setTextoTlfPpalRpr1(arrOfStrTlfPpalRpr1[1]);
        alumnoDTO.setCodoperadorasecrep1(arrOfStrTlfSecRpr1[0]);
        alumnoDTO.setTextoTlfSecRpr1(arrOfStrTlfSecRpr1[1]);
        alumnoDTO.setEmailRpr1(alumno.getRpr1().getEmailRpr());
        alumnoDTO.setTipoDocRep2(alumno.getRpr2().getTipoDocRpr());
        alumnoDTO.setNumDocRep2(alumno.getRpr2().getNumDocRpr());
        alumnoDTO.setPrimNombRpr2(alumno.getRpr2().getPrimNombRpr());
        alumnoDTO.setSegNombRpr2(alumno.getRpr2().getSegNombRpr());
        alumnoDTO.setPrimApellRpr2(alumno.getRpr2().getPrimApellRpr());
        alumnoDTO.setSegApellRpr2(alumno.getRpr2().getSegApellRpr());
        alumnoDTO.setSexoRpr2(alumno.getRpr2().getSexoRpr());
        alumnoDTO.setFechNacRpr2(alumno.getRpr2().getFechNacRpr());
        alumnoDTO.setEdadRpr2(alumno.getRpr2().getEdadRpr());
        alumnoDTO.setEdoCivRpr2(alumno.getRpr2().getEdoCivRpr());
        alumnoDTO.setParRpr2(alumno.getParRpr2());
        alumnoDTO.setTextoDirPpalRpr2(arrOfStrDirPpalRpr2[0]);
        alumnoDTO.setEstadodirppalrep2(arrOfStrDirPpalRpr2[1]);
        alumnoDTO.setMunicipiodirppalrep2(arrOfStrDirPpalRpr2[2]);
        alumnoDTO.setCiudaddirppalrep2(arrOfStrDirPpalRpr2[3]);
        alumnoDTO.setParroquiadirppalrep2(arrOfStrDirPpalRpr2[4]);
        alumnoDTO.setCodpostaldirppalrep2(arrOfStrDirPpalRpr2[5]);
        alumnoDTO.setTextoDirSecRpr2(arrOfStrDirSecRpr2[0]);
        alumnoDTO.setEstadodirsecrep2(arrOfStrDirSecRpr2[1]);
        alumnoDTO.setMunicipiodirsecrep2(arrOfStrDirSecRpr2[2]);
        alumnoDTO.setCiudaddirsecrep2(arrOfStrDirSecRpr2[3]);
        alumnoDTO.setParroquiadirsecrep2(arrOfStrDirSecRpr2[4]);
        alumnoDTO.setCodpostaldirsecrep2(arrOfStrDirSecRpr2[5]);
        alumnoDTO.setCodoperadorappalrep2(arrOfStrTlfPpalRpr2[0]);
        alumnoDTO.setTextoTlfPpalRpr2(arrOfStrTlfPpalRpr2[1]);
        alumnoDTO.setCodoperadorasecrep2(arrOfStrTlfSecRpr2[0]);
        alumnoDTO.setTextoTlfSecRpr2(arrOfStrTlfSecRpr2[1]);
        alumnoDTO.setEmailRpr2(alumno.getRpr2().getEmailRpr());
        return alumnoDTO;
    }
}
