version: "3.9"
services:
  sigadb:
    image: mariadb
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: siga
      MARIADB_ROOT_HOST: localhost

    restart: always
  sigaservice:
    container_name: siga
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    env_file: .env
    depends_on:
      - sigadb
    restart: always





