version: '3.9'
services:
  siga-api:
    container_name: siga-api
    image: siga-api:1.0.0
    build: .
    ports:
      - "8090:8080"
    environment:
      - SIGA_DB_USERNAME
      - SIGA_DB_PASSWORD
      - SIGA_DB_SERVERNAME
      - SIGA_DB_PORT
      - SIGA_DB_NAME
    depends_on:
      - siga_db
    volumes:
        - ./src:/app/src
  siga_db:
    container_name: siga_db
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=siga
      - MYSQL_USER=user
      - MYSQL_PASSWORD=sigadbpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
volumes:
  mysql_db:
    driver: local







